### ISSUE TITLE
Help please! Trying to create a Krona chart for the metagenomic analysis of a hot spring

### ISSUE THREAD

**Issue by tborton** [marbl/Krona#46]
Hi, if someone could help walk me through this I would be ETERNALLY grateful.

I downloaded KronaTools-2.7 as well as the KronaExcelTemplate.

When I tried to instal it (using install_Mac_all_users and install_Mac) I immediately come up with this error message:
 “install_Mac_all_users” is damaged and can’t be opened. You should move it to the Trash.

I did try to play around with the example excel template but I am not sure where to begin with this.  

I have 1200 OTUs that I would like to incorporate, I am sure that no other schmuck is doing it manually so I came here to ask for help :/

I am not sure where to go from here.. Unfortunately I am not the most computer savvy individual, if there is a relatively straight forward way to do this I would super super appreciate some direction.

Thanks!!

**Comment by deepthoughts** [comment]
1) Open Terminal :  (Cmd+Spacebar) and type "Terminal".

2) Type this command:
```
curl -LOk https://github.com/marbl/Krona/releases/download/v2.7/KronaTools-2.7.tar
```

3) Untar the file

```
tar xvf KronaTools-2.7.tar
```

4) change the directory to Krona
```
cd KronaTools-2.7
```
5) Install Krona using Perl script
```
./install.pl
```

This should install Krona on your computer.

**Comment by tborton** [comment]
Ok after I clicked enter after the install I got this error message

Creating links...
ln: /usr/local/bin/ktClassifyBLAST: Permission denied

ERROR: Couldn't link files to /usr/local/bin.  Do you have permission?
(Use "--prefix <path>" to change install location)

**Comment by deepthoughts** [comment]
What is the output of this command ?

```
pwd
```

**Comment by tborton** [comment]
These were the four lines before:
x KronaTools-2.7/README.txt
x KronaTools-2.7/LICENSE.txt
Taylors-MBP:~ taylorboyd$ cd KronaTools-2.7
Taylors-MBP:KronaTools-2.7 taylorboyd$ ./install.pl

And this was the line after:
Taylors-MBP:KronaTools-2.7 taylorboyd$ 

Thanks so much for your help!!

**Comment by deepthoughts** [comment]
It means that you do not have permission on /usr/local/bin folder. 

Make sure you are in KronaTools-2.7  directory
and install with the --prefix argument as it says above. 

```
 ./install.pl --prefix /Users/taylorboyd
```

**Comment by tborton** [comment]
Ah! Awesome, you are the best! Now, sorry for all of my stupid questions, but is there a way to upload a fastafile? Or how can I import my data? 

Sorry again! And thank you!!

**Comment by deepthoughts** [comment]
No problem. You are almost there. What format is your data?  Is it Blast results?  Can you post single line from your results?

**Comment by tborton** [comment]
So I have my actual data in a fastafile but that is just OTUs.  I classified it using blast, but I did it manually.  I tried downloading the results, so I have the Hit Table in text format.. I tried a few of the other dl options but it would just give me 1 OTU at a time :/

**Comment by deepthoughts** [comment]
Do you have Blast results? Are all the results in a text file?

**Comment by deepthoughts** [comment]
Have you ran this command? in the KronaTools-2.7 directory. This will download all the relevant taxonomy information needed to make the chart. 
```
updateAccessions.sh
```
Next, you should run this command to perform the actual import. 

```
./ImportBLAST.pl  blast_output_file -o blast_results.html
```

**Comment by tborton** [comment]
I have all of my classifications in an excel file with columns for OTU, Domain, Phylum, Class, Order, Family, Genus and Species etc... Is that what you mean? I wasn't able to find how to download my Blast results nicely from NCBI... So the text file that I have is the closest thing but it is just the top 100 hits for each OTU with the accession numbers, %identity, alignment length etc, etc..

**Comment by deepthoughts** [comment]
Can you post a sample line from the excel file?

**Comment by deepthoughts** [comment]
Have you ran this command? in the KronaTools-2.7 directory. This will download all the relevant taxonomy information needed to make the chart. 
```
updateAccessions.sh
```
Next, you should run this command to perform the actual import. 

blast_output_file should be exported from excel as tab delimited file. 
```
./ImportBLAST.pl  blast_output_file -o blast_results.html
```

**Comment by tborton** [comment]
OTU_1031	Bacteria	Actinobacteria	1	Actinobacteria	Micrococcales	Intrasporangiaceae	Aquipuribacter	Aquipuribacter hungaricus	5

**Comment by tborton** [comment]
I got this...
Taylors-MBP:KronaTools-2.7 taylorboyd$ updateAccessions.sh
-bash: updateAccessions.sh: command not found
Taylors-MBP:KronaTools-2.7 taylorboyd$

**Comment by deepthoughts** [comment]
Try to put "." in front of that command. "." means you are calling the command from the current directory.

Sorry this is the updated command
```
./updateAccessions.sh
```

**Comment by tborton** [comment]
OK it is fetching lots of stuff now :) Seriously, I cannot thank you enough for walking me through this! I would be lost without you!

**Comment by deepthoughts** [comment]
I have been through that stage. Just hang on. One thing I am not sure about the results is that previously you indicated that you have accession numbers, %identity, alignment length, etc. But your sample line does not show it? 
Ideally, Krona would be easier if you had Blast results in "accession numbers, %identity, alignment length" format as described in
 http://www.metagenomics.wiki/tools/blast/blastn-output-format-6

**Comment by tborton** [comment]
Oh sorry! That was from my excel table, here is from the Blast table
OTU_1	gi|1109168029|ref|NR_144613.1|	OTU_1	NR_144613.1	85.609	271	33	6	6	273	506	773	3.51e-75	279

**Comment by tborton** [comment]
it says: # Fields: query id, subject ids, query acc.ver, subject acc.ver, % identity, alignment length, mismatches, gap opens, q. start, q. end, s. start, s. end, evalue, bit score

**Comment by tborton** [comment]
Hey again! So I did have to move somewhere and close my computer.. then I got this error message..  Should I just try to run again?

Fetching accession2taxid/prot.accession2taxid.gz...
   Fetching checksum...
   Checksum for accession2taxid/prot.accession2taxid.gz matches server.
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Update failed.
   Building accession2taxid failed (see errors above). Issues can be tracked and reported at https://github.com/marbl/Krona/issues.

Taylors-MBP:KronaTools-2.7 taylorboyd$

**Comment by deepthoughts** [comment]
I guess you do not have command line tools on your mac. 
Follow instructions on this link 
http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/

**Comment by tborton** [comment]
OK! Did that and ran updateAccessions.sh again to see if it would go to completion.. I just got this and it seems to be "done" 
Sorting dead_nucl.accession2taxid.gz...
Sorting dead_prot.accession2taxid.gz...
Sorting dead_wgs.accession2taxid.gz...
Sorting nucl_est.accession2taxid.gz...
Sorting nucl_gb.accession2taxid.gz...

**Comment by deepthoughts** [comment]
Nice. 

Run this command to make the scripts as your current directory

```
cd ~/KronaTools-2.7/scripts
```

and specify the complete location of the "blast_output_file" in this command below.

For example: /Users/taylorboyd/blast_output_file.txt

```
./ImportBLAST.pl  blast_output_file.txt -o blast_results.html
```

**Comment by tborton** [comment]
So I did both of those and there was no output...

**Comment by deepthoughts** [comment]
Did you get error message or any other message in the terminal?

**Comment by tborton** [comment]
Nothing after the last line here:
Sorting nucl_gss.accession2taxid.gz...
Sorting nucl_wgs.accession2taxid.gz...
Sorting prot.accession2taxid.gz...
cd ~/KronaTools-2.7/scripts
./ImportBLAST.pl  blast_output_file.txt -o blast_results.html

**Comment by deepthoughts** [comment]
Check the scripts folder within Krona folder

**Comment by deepthoughts** [comment]
Where is your Blast output file located?

**Comment by tborton** [comment]
![screen shot 2017-04-11 at 4 25 17 pm](https://cloud.githubusercontent.com/assets/27034806/24935114/ae2d875c-1ed4-11e7-8213-025ff491f930.png)
This is what the scripts folder looks like.  The blast output file is just downloaded to my desktop

**Comment by deepthoughts** [comment]
You need to give the exact location of your Blast output file to this command. 

```
./ImportBLAST.pl  <location of your blast results> -o blast_results.html
```
Let us say you have your Blast results at 

/Users/taylorboyd/Desktop/<NAME OF YOUR BLAST RESULTS FILE with extension> 

Give that location to the script above. You are very close. 

Basically, all you need to do is provide the location of your blast results to that Perl script.

**Comment by tborton** [comment]
Ok. I did that! This is what I have so far...

"cd ~/KronaTools-2.7/scripts
./ImportBLAST.pl </Users/taylorboyd/Desktop/ETV3ER9101R-Alignment.txt> -o blast_results.html

Merging sorted..."

Is that a good sign? Or...

**Comment by deepthoughts** [comment]
Almost. Just remove < > from the from that command:

```
cd ~/KronaTools-2.7/scripts
./ImportBLAST.pl  /Users/taylorboyd/Desktop/ETV3ER9101R-Alignment.txt  -o blast_results.html
```

**Comment by tborton** [comment]
Seriously I wish I could buy you a beer at the end of all of this! I appreciate your patience with my uselessness at this!

Along those lines.. I typed this in there, and again no outpt... Just blank space


cd ~/KronaTools-2.7/scripts
./ImportBLAST.pl  /Users/taylorboyd/Desktop/ETV3ER9101R-Alignment.txt  -o blast_results.html

**Comment by deepthoughts** [comment]
No problem.
Any messages on the terminal?

 Can you check your scripts folder that you took the screenshot before?
Look for the blast_results.html file.

This command says that run this script on this file and output the contents to the "blast_results.html" in the current folder which happens to be script folder.

**Comment by tborton** [comment]
So I might have just broken it :/  I tried to copy and paste the commands one more time and pushed enter before I realized the last half of the line was missing.. Now it seems to be frozen and I can't type anything.. My computer is pretty slow, so maybe I should just give it some time?

**Comment by deepthoughts** [comment]
It is fine. At least, now you are familiar with the commands. You can close the terminal window if you can and start again with those last two commands.

**Comment by tborton** [comment]
Got this message, do I have to do the same thing we did with Accession? Like do I just need to do this? ./updateTaxonomy.sh??

Loading taxonomy...
Taxonomy not found in /Users/taylorboyd/KronaTools-2.7/taxonomy. Was updateTaxonomy.sh run? at /Users/taylorboyd/KronaTools-2.7/scripts/../lib/KronaTools.pm line 1376.

**Comment by deepthoughts** [comment]
Yes try to run them in that folder.

In terminal type

```
 cd /Users/taylorboyd/KronaTools-2.7/scripts
```

```
./updateTaxonomy.sh
```

**Comment by tborton** [comment]
Hmmm so I see the updateTaxonomy.sh file in my KronaTools folder and an empty taxonomy folder.. But I got this message :  

Taylors-MBP:scripts taylorboyd$  cd /Users/taylorboyd/KronaTools-2.7/scripts
Taylors-MBP:scripts taylorboyd$ ./updateTaxonomy.sh
-bash: ./updateTaxonomy.sh: No such file or directory

**Comment by deepthoughts** [comment]
Sorry, that script is in /Users/taylorboyd/KronaTools-2.7/ folder

Try this
```
cd /Users/taylorboyd/KronaTools-2.7/
```
```
./updateTaxonomy.sh
```

**Comment by tborton** [comment]
OK! It says "Finished" hurray! 

Should I go back to this now:
cd ~/KronaTools-2.7/scripts
./ImportBLAST.pl /Users/taylorboyd/Desktop/ETV3ER9101R-Alignment.txt -o blast_results.html

Also, you asked about a blast_results.html  in the scripts folder.. there is not, there is an ImportBLAST.pl and a ClassifyBLAST.pl as well as ImportMETAREP-BLAST.pl.

Those are the only three files with "blast" in the name.

**Comment by deepthoughts** [comment]
Yes, try these commands:

```
cd ~/KronaTools-2.7/scripts
```
```
./ImportBLAST.pl /Users/taylorboyd/Desktop/ETV3ER9101R-Alignment.txt -o blast_results.html
```

**Comment by tborton** [comment]
OK I did that, I got an error message asking if updateAccessions.sh was run, so I just ran that again.. I thought it was doing something, but it seems to be cycling now...

Loading taxonomy...
Importing /Users/taylorboyd/Desktop/ETV3ER9101R-Alignment.txt...
   Classifying BLAST results...
ERROR: Sorted accession to taxID list not found. Was updateAccessions.sh run?
Taylors-MBP:scripts taylorboyd$ cd /Users/taylorboyd/KronaTools-2.7/
Taylors-MBP:KronaTools-2.7 taylorboyd$ ./updateAccessions.sh
Fetching accession2taxid/dead_nucl.accession2taxid.gz...
   Fetching checksum...
   Checksum for accession2taxid/dead_nucl.accession2taxid.gz matches server.
Fetching accession2taxid/dead_prot.accession2taxid.gz...
   Fetching checksum...
   Checksum for accession2taxid/dead_prot.accession2taxid.gz matches server.
Fetching accession2taxid/dead_wgs.accession2taxid.gz...
   Fetching checksum...
   Checksum for accession2taxid/dead_wgs.accession2taxid.gz matches server.
Fetching accession2taxid/nucl_est.accession2taxid.gz...
   Fetching checksum...
   Checksum for accession2taxid/nucl_est.accession2taxid.gz matches server.
Fetching accession2taxid/nucl_gb.accession2taxid.gz...
   Fetching checksum...
   Checksum for accession2taxid/nucl_gb.accession2taxid.gz matches server.
Fetching accession2taxid/nucl_gss.accession2taxid.gz...
   Fetching checksum...
   Checksum for accession2taxid/nucl_gss.accession2taxid.gz matches server.
Fetching accession2taxid/nucl_wgs.accession2taxid.gz...

**Comment by deepthoughts** [comment]
Hmm.. Can you check your taxonomy folder ? 

can you list the contents of taxnomy folder using this command ?

```
ls ~/KronaTools-2.7/taxonomy
```

I guess if the error persists, I would suggest to delete the Krona folder and start over with downloading and installing.  Ideally, that last step should produce .html file which you can view it in any web browser.

**Comment by tborton** [comment]
OK I did that and I get this

Taylors-MBP:KronaTools-2.7 taylorboyd$ ls ~/KronaTools-2.7/taxonomy
accession2taxid			all.accession2taxid.sorted	taxonomy.tab

What do you think? Start over with a new Krona folder?

**Comment by tborton** [comment]
And when I open the taxonomy folder in the KronaTools folder there is nothing

**Comment by deepthoughts** [comment]
Not sure why you are not getting results. I guess the best course is to start over. It should not take too long and this time.

Using terminal

DELETE your existing KronaTools-2.7.tar

1) BE VERY careful with this first command. It deletes the Krona folder. Make sure you enter this correctly. 
```
rm -rf /Users/taylorboyd/KronaTools-2.7/scripts
```
2) Type this command in the terminal window:
```
curl -LOk https://github.com/marbl/Krona/releases/download/v2.7/KronaTools-2.7.tar
```

3) Untar the file

```
tar xvf KronaTools-2.7.tar
```

4) change the directory to Krona
```
cd KronaTools-2.7
```
5) Install Krona using Perl script
```
./install.pl
```

This should install Krona on your computer. 

Next, 


6) Just run updateTaxonomy.sh NOT updateAccessions.sh

```
~/KronaTools-2.7/updateTaxonomy.sh

```

7) cd to scripts

```
cd ~/KronaTools-2.7/scripts
```
8) 
Run Krona blast script

```
./ImportBLAST.pl /Users/taylorboyd/Desktop/ETV3ER9101R-Alignment.txt -o /Users/taylorboyd/Desktop/blast_results.html
```

9) Check your desktop folder if you can see blast_results.html

This is the summary of all the commands so far. Hopefully, this will work. I will probably reply in the morning.

**Comment by tborton** [comment]
So I did all that and I kept running into error messages last night, got frustrated and went to bed. BUT I started fresh again this morning and lookie here!! I am so excited!! Thank you SO SO SO much @deepthoughts you are the BEST! Now I just need to lay around with the features :D 
![screen shot 2017-04-12 at 7 17 13 am](https://cloud.githubusercontent.com/assets/27034806/24962285/605f81a2-1f50-11e7-8b96-cc5a0f5bdeb8.png)

**Comment by tborton** [comment]
Hi!! Me again :/ one final (hopefully) grasp for help on this... I went through my blast results file and got rid of all of the OTUs that were not 85% match or greater. I just tried to run it again to get a new krona chart and got this error message... 

Taylors-MBP:scripts taylorboyd$ ./ImportBLAST.pl /Users/taylorboyd/Desktop/ETV3ER9101R-Alignment.txt -o /Users/taylorboyd/Desktop/blast_results.html
Loading taxonomy...
Importing /Users/taylorboyd/Desktop/ETV3ER9101R-Alignment.txt...
   Classifying BLAST results...
ERROR: Sorted accession to taxID list not found. Was updateAccessions.sh run?
Taylors-MBP:scripts taylorboyd$ 

Any advice here?  THANKS!

**Comment by deepthoughts** [comment]
Not sure what went wrong this time, especially given that it ran first time with same file. Is your Alignment file correctly formatted after you got rid of the OTUs less than 85% match?

**Comment by ondovb** [comment]
Hi @tborton. I think what may have happened is that commands were run before others were finished, causing some unpredictable things to happen. When a command finishes, you will see the prompt again (like "`Taylors-MBP:scripts taylorboyd$`"). In any event, if this file is truly missing now (it would be `~/KronaTools-2.7/taxonomy/all.accession2taxid.sorted`), you will need to run `./updateAccessions.sh` from the KronaTools directory again. The process should take around half an hour.

**Comment by ondovb** [comment]
Assuming this has been resolved; please re-open if there are further issues.

**Comment by libertinerosessanchez** [comment]
I still get the following error and cannot create a krona chart.
Taxonomy not found in /Users/LibethSanchez/krona/Krona-master/KronaTools/taxonomy. Was updateTaxonomy.sh run? at /Users/LibethSanchez/krona/Krona-master/KronaTools/scripts/../lib/KronaTools.pm line 1529
